import Head from "next/head";
import Header from "../components/Header";
import Footer from "../components/Footer";
import App from "../components/App";

export default function Home() {
  return (
    <>
      <Head>
        <title>keeper-app-part-3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <App />
      <Footer></Footer>
    </>
  );
}